name: Ezored - iOS

on: [push]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "macOS Latest Clang", os: macos-latest, target: "ios" }
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade PIP
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Display Python version
        run: python --version

      - name: Display PIP version
        run: pip --version

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: "3.15.0"

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: "1.10.0"

      - name: Ezored - Install python dependencies
        run: pip install -r requirements.txt

      - name: Ezored - Install glue code tool
        run: |
          python make.py gluecode setup
          python make.py gluecode version

      - name: Ezored - Setup conan
        run: python make.py conan setup

      - name: Ezored - Prepare
        run: python make.py target ${{ matrix.config.target }} prepare

      - name: Ezored - Build
        run: python make.py target ${{ matrix.config.target }} build

      - name: Ezored - Package
        run: python make.py target ${{ matrix.config.target }} package --no-framework

      - name: Ezored - Dist generate
        run: python make.py target ${{ matrix.config.target }} dist generate

      - name: Ezored - Dist upload
        env:
          EZORED_AWS_KEY_ID: ${{ secrets.EZORED_AWS_KEY_ID }}
          EZORED_AWS_SECRET_KEY: ${{ secrets.EZORED_AWS_SECRET_KEY }}
        run: python make.py target ${{ matrix.config.target }} dist upload --force
